import * as React from "react";
import { useState } from "react";
// import { makeStyles } from "@material-ui/core";
import { Tabs, Tab } from "@mui/material";
import { HashLink } from "react-router-hash-link";

/**
 * @description A navigation bar for desktop screens.
 *
 * @param {number} tabValue - The value of the currently selected tab.
 * @param {function(number)} setTabValue - A function to set the value of the selected tab.
 * @param {Location} location - The location object from the `react-router-dom` package, representing the current URL.
 * @param {Object} classes - The classes object generated by the `makeStyles` function from `@material-ui/core`, containing the styles for the component.
 * @returns {React.Component} The rendered desktop navigation menu.
 *
 */
function DesktopNav() {
  // const [tabValue, setTabValue] = useState(0);
  const [value, setValue] = useState(0);
  // const location = useLocation();

  // useEffect(() => {
  //   setTabValue(links.findIndex((link) => link.path === location.pathname));
  // }, [location.pathname]);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <Tabs value={value} onChange={handleChange}>
      <Tab label="Section 1" component={HashLink} to="#home " smooth />
      <Tab label="Section 2" component={HashLink} to="#services" smooth />
      <Tab label="Section 3" component={HashLink} to="#testimonial" smooth />
    </Tabs>
  );
}
export default DesktopNav;
